### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by skyworldp** [K9100ii/gtaxl-manifests#2]
Can I get the devices tree to build a newer version （Android 13 or 14）Lineage OS ？

**Comment by K9100ii** [comment]
> Can I get the devices tree to build a newer version （Android 13 or 14）Lineage OS ？

Please wait until I release LineageOS 20.0 (based on Android 13) builds in the coming days myself (on the XDA forums) for a manifest - I only (prepare and) release manifests as soon as I release builds, and therefore there is no 20.0 manifest in this repository.

Also, there is currently no work for LineageOS 21.0 (based on 14) - That is to be looked at, especially for the state of things for older devices like these ones. Please be patient for that all.

**Comment by 2spirit** [comment]
Good news for 20.0 version ! Thanks @K9100ii  ;)

**Comment by K9100ii** [comment]
Manifest is up on branch lineage-20.0

**Comment by 2spirit** [comment]
Great !  I will try to build a MicroG version ;-)
